### ISSUE TITLE
Use for 10k thermistor? (Closed/Solved)

### ISSUE THREAD

**Issue by Aubrey4485** [RobTillaart/MultiMap#9]
This is not really an issue. Feel free to label as solved right away, I just do not know how to simply message author of this library otherwise?? LOL
Is it possible to use multimap with an NTC thermistor as long as I have made a table of known raw analog values and resistances (my IN[]) matching associated temperatures (my OUT[])?
Only reason I ask is cause i have used multimap before for flow sensors with success but Im not a coder by any means and the NTC example provided is confusing the hell out of me!! LOL

thanks

**Comment by RobTillaart** [comment]
Thanks for this question.
Will come back to it tomorrow.

**Comment by RobTillaart** [comment]
Essentially yes if you have the points you can.

**Comment by RobTillaart** [comment]
You must take care that the input array is in ascending order. They do not need to be equidistant, so you can have more points in the range you need the highest precision.

**Comment by RobTillaart** [comment]
> the NTC example provided is confusing the hell out of me!! LOL

The example compares the formula based version with the **MultiMap()** lookup. That formula is indeed not a trivial one.
For you the only part that matters is the input array and output array, and you should trim them down to the range you are using, optionally add 2 extremes at both ends to catch outliers.

**Comment by RobTillaart** [comment]
One point of importance when using NTC's is that you must take care of a very stable power supply.
Any fluctuations on the power supply will appear as a fluctuation in temperature. 
If these fluctuations are within acceptable accuracy there is no problem, otherwise it is a point of attention.
E.g. you can average multiple analog reads to suppress these fluctuations.

**Comment by Aubrey4485** [comment]
Holy mackerel! Thank you so so much for the detailed answer. I really do appreciate it and enjoy your libraries and contributions to the community.

i am glad to hear from you that multimap will work with a more log type of curve. I had no idea. The NTC example makes sense now . I will just use multimap as I always do and heed your advice. I would like to stay away from the formula method as I do not really understand this level of math.

thanks again 👍🏼.

**Comment by RobTillaart** [comment]
Multimap can do almost any function with one parameter, the only conditions are that
- for every x there should be an y
- it should be continuous
- no infinities as interpolating becomes inaccurate or impossible
- no dividing by 0 e.g.  sin(1/x) becomes hard around zero
- the number of solutions for F''(x) times 2 indicates the minimum of interpolation points. 

You're welcome
If this solves your question, you may close the issue.
